#!/bin/bash
if [ "$#" != "2" ]; then
    echo "for lines in input, prepend the date and time, and write the result to"
    echo "file, or stdout if file is '-'"
    echo "usage: tlog <log name> <log file>"
    exit 1
fi

if [ "$2" != "-" ]; then
    echo > $2
fi

while read -r line;
do
    CMD='echo $(date +"%Y-%m-%d | %H:%M:%S%z") | $1 | ${line}'
    if [ "$2" == "-" ]; then
        echo "$(date +"%Y-%m-%d | %H:%M:%S%z") | $1 | ${line}"
    else
        echo "$(date +"%Y-%m-%d | %H:%M:%S%z") | $1 | ${line}" >> $2
        echo ${line}
    fi
done

